In [111]:
# Dependencies
from bs4 import BeautifulSoup
import requests
import os
import pandas as pd
from splinter import Browser
from webdriver_manager.chrome import ChromeDriverManager
#import numpy as np
#%matplotlib inline

In [112]:
executable_path = {'executable_path': r'C:\\Users\\Alpagino\\.wdm\\drivers\\chromedriver\\win32\\105.0.5195\\chromedriver.exe'}
browser = Browser('chrome', **executable_path, headless=False)

In [113]:
# Stack Overflow URL to scrape
url = 'https://www.nrcs.usda.gov/wps/portal/nrcs/detail/national/home/?cid=nrcs143_013697'
url_state = 'https://en.wikipedia.org/wiki/Federal_Information_Processing_Standard_state_code'
browser.visit(url)
html = browser.html
soup = BeautifulSoup(html, 'html.parser')

In [114]:
tables = pd.read_html(url)
tables

[                                                   FIPS        Name State
 0                                                 01001     Autauga    AL
 1                                                 01003     Baldwin    AL
 2                                                 01005     Barbour    AL
 3                                                 01007        Bibb    AL
 4                                                 01009      Blount    AL
 ...                                                 ...         ...   ...
 3228                                              72153       Yauco    PR
 3229                                              78010   St. Croix    VI
 3230                                              78020    St. John    VI
 3231                                              78030  St. Thomas    VI
 3232  //<![CDATA[ var $s = {} var isClick = false; $...         NaN   NaN

 [3233 rows x 3 columns],
                                                    FIPS        Name State
 0                                                 01001     Autauga    AL
 1                                                 01003     Baldwin    AL
 2                                                 01005     Barbour    AL
 3                                                 01007        Bibb    AL
 4                                                 01009      Blount    AL
 ...                                                 ...         ...   ...
 3228                                              72153       Yauco    PR
 3229                                              78010   St. Croix    VI
 3230                                              78020    St. John    VI
 3231                                              78030  St. Thomas    VI
 3232  //<![CDATA[ var $s = {} var isClick = false; $...         NaN   NaN

 [3233 rows x 3 columns],
                                                    FIPS        Name State
 0                                                 01001     Autauga    AL
 1                                                 01003     Baldwin    AL
 2                                                 01005     Barbour    AL
 3                                                 01007        Bibb    AL
 4                                                 01009      Blount    AL
 ...                                                 ...         ...   ...
 3231                                              78030  St. Thomas    VI
 3232  //<![CDATA[ var $s = {} var isClick = false; $...         NaN   NaN
 3233  You are Here: Home  / County FIPS Codes  Stay ...         NaN   NaN
 3234  var $ = document; \tvar head = $.getElementsBy...         NaN   NaN
 3235  NRCS Home | USDA.gov | Site Map | Civil Rights...         NaN   NaN

 [3236 rows x 3 columns],
                                                    0
 0  //<![CDATA[ var $s = {} var isClick = false; $...,
                                                    0
 0  //<![CDATA[ var $s = {} var isClick = false; $...,
                                                    0
 0  You are Here: Home  / County FIPS Codes  Stay ...,
                                                    0
 0  You are Here: Home  / County FIPS Codes  Stay ...,
                                                    0
 0  You are Here: Home  / County FIPS Codes  Stay ...,
          FIPS        Name                                              State
 0      1001.0     Autauga                                                 AL
 1      1003.0     Baldwin                                                 AL
 2      1005.0     Barbour                                                 AL
 3      1007.0        Bibb                                                 AL
 4      1009.0      Blount                                                 AL
 ...       ...         ...                                                ...
 3228  72153.0       Yauco                                                 PR
 3229  78010.0   St. Croix                                                 VI
 3230  78020.0    St. John                                                 VI
 3231  78030.0  St. Thomas                                                 VI
 3232      NaN         NaN  var $ = document; \tvar head = $.getElementsBy...

 [3233 rows x 3 columns],
                                                    FIPS        Name State
 0                                                 01001     Autauga    AL
 1                                                 01003     Baldwin    AL
 2                                                 01005     Barbour    AL
 3                                                 01007        Bibb    AL
 4                                                 01009      Blount    AL
 ...                                                 ...         ...   ...
 3228                                              72153       Yauco    PR
 3229                                              78010   St. Croix    VI
 3230                                              78020    St. John    VI
 3231                                              78030  St. Thomas    VI
 3232  var $ = document; \tvar head = $.getElementsBy...         NaN   NaN

 [3233 rows x 3 columns],
                                                    FIPS        Name State
 0                                                 01001     Autauga    AL
 1                                                 01003     Baldwin    AL
 2                                                 01005     Barbour    AL
 3                                                 01007        Bibb    AL
 4                                                 01009      Blount    AL
 ...                                                 ...         ...   ...
 3228                                              72153       Yauco    PR
 3229                                              78010   St. Croix    VI
 3230                                              78020    St. John    VI
 3231                                              78030  St. Thomas    VI
 3232  var $ = document; \tvar head = $.getElementsBy...         NaN   NaN

 [3233 rows x 3 columns],
        FIPS        Name State
 0      1001     Autauga    AL
 1      1003     Baldwin    AL
 2      1005     Barbour    AL
 3      1007        Bibb    AL
 4      1009      Blount    AL
 ...     ...         ...   ...
 3227  72151     Yabucoa    PR
 3228  72153       Yauco    PR
 3229  78010   St. Croix    VI
 3230  78020    St. John    VI
 3231  78030  St. Thomas    VI

 [3232 rows x 3 columns],
     0                                                  1
 0 NaN  NRCS Home | USDA.gov | Site Map | Civil Rights...,
                                                    0
 0  NRCS Home | USDA.gov | Site Map | Civil Rights...,
                                                    0
 0  NRCS Home | USDA.gov | Site Map | Civil Rights...]

In [115]:
county_fips = tables[0]
county_fips.head()

    FIPS     Name State
0  01001  Autauga    AL
1  01003  Baldwin    AL
2  01005  Barbour    AL
3  01007     Bibb    AL
4  01009   Blount    AL

In [116]:
len(county_fips)

3233

In [117]:
county_fips.head(100)

     FIPS      Name State
0   01001   Autauga    AL
1   01003   Baldwin    AL
2   01005   Barbour    AL
3   01007      Bibb    AL
4   01009    Blount    AL
..    ...       ...   ...
95  04003   Cochise    AZ
96  04005  Coconino    AZ
97  04007      Gila    AZ
98  04009    Graham    AZ
99  04011  Greenlee    AZ

[100 rows x 3 columns]

In [118]:
state_tables = pd.read_html(url_state)
state_tables

[                Name Alpha code  Numeric code  \
 0            Alabama         AL             1
 1             Alaska         AK             2
 2     American Samoa         AS            60
 3   American Samoa *        NaN             3
 4            Arizona         AZ             4
 ..               ...        ...           ...
 69       Wake Island         WI            79
 70        Washington         WA            53
 71     West Virginia         WV            54
 72         Wisconsin         WI            55
 73           Wyoming         WY            56

                                   Status
 0                        State; counties
 1                        State; boroughs
 2   Outlying area under U.S. sovereignty
 3               (FIPS 5-1 reserved code)
 4                        State; counties
 ..                                   ...
 69       Minor outlying island territory
 70                       State; counties
 71                       State; counties
 72                       State; counties
 73                       State; counties

 [74 rows x 4 columns],
     EAS code                                      Maritime area
 0         57        Pacific coast from Washington to California
 1         58                                      Alaskan coast
 2         59                                     Hawaiian coast
 3         61                              American Samoa waters
 4         65            Mariana Islands waters (including Guam)
 5         73              Atlantic coast from Maine to Virginia
 6         75  Atlantic coast from North Carolina to Florida,...
 7         77                                     Gulf of Mexico
 8         91                                      Lake Superior
 9         92                                      Lake Michigan
 10        93                                         Lake Huron
 11        94  St. Clair River, Detroit River, and Lake St. C...
 12        96                                          Lake Erie
 13        97                     Niagara River and Lake Ontario
 14        98                                 St. Lawrence River,
    .mw-parser-output .navbar{display:inline;font-size:88%;font-weight:normal}.mw-parser-output .navbar-collapse{float:left;text-align:left}.mw-parser-output .navbar-boxtext{word-spacing:0}.mw-parser-output .navbar ul{display:inline-block;white-space:nowrap;line-height:inherit}.mw-parser-output .navbar-brackets::before{margin-right:-0.125em;content:"[ "}.mw-parser-output .navbar-brackets::after{margin-left:-0.125em;content:" ]"}.mw-parser-output .navbar li{word-spacing:-0.125em}.mw-parser-output .navbar a>span,.mw-parser-output .navbar a>abbr{text-decoration:inherit}.mw-parser-output .navbar-mini abbr{font-variant:small-caps;border-bottom:none;text-decoration:none;cursor:inherit}.mw-parser-output .navbar-ct-full{font-size:114%;margin:0 7em}.mw-parser-output .navbar-ct-mini{font-size:114%;margin:0 4em}vteUnited States state-related lists  \
 0   List of states and territories of the United S...
 1                                        Demographics
 2                                             Economy
 3                                         Environment
 4                                           Geography
 5                                          Government
 6                                              Health
 7                                             History
 8                                                 Law
 9                                       Miscellaneous
 10                         Category  Commons  Portals

    .mw-parser-output .navbar{display:inline;font-size:88%;font-weight:normal}.mw-parser-output .navbar-collapse{float:left;text-align:left}.mw-parser-output .navbar-boxtext{word-spacing:0}.mw-parser-output .navbar ul{display:inline-block;white-space:nowrap;line-height:inherit}.mw-parser-output .navbar-brackets::before{margin-right:-0.125em;content:"[ "}.mw-parser-output .navbar-brackets::after{margin-left:-0.125em;content:" ]"}.mw-parser-output .navbar li{word-spacing:-0.125em}.mw-parser-output .navbar a>span,.mw-parser-output .navbar a>abbr{text-decoration:inherit}.mw-parser-output .navbar-mini abbr{font-variant:small-caps;border-bottom:none;text-decoration:none;cursor:inherit}.mw-parser-output .navbar-ct-full{font-size:114%;margin:0 7em}.mw-parser-output .navbar-ct-mini{font-size:114%;margin:0 4em}vteUnited States state-related lists.1
 0   List of states and territories of the United S...
 1   Population African American Amish Asian Birth ...
 2   Billionaires Budgets Companies Credit ratings ...
 3   Botanical gardens Carbon dioxide emissions Par...
 4   Area Bays Beaches Coastline Elevation Extreme ...
 5   Agriculture commissioners Attorneys general Ca...
 6   Fertility rates Hospitals Human Development In...
 7   Date of statehood Name etymologies Historical ...
 8   Abortion Age of consent Alcohol Dry communitie...
 9   Abbreviations Airports Bus transit systems Cas...
 10                         Category  Commons  Portals                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ,
      vteGeocode systems                               vteGeocode systems.1
 0  Administrative codes  FIPS country code (FIPS 10-4) FIPS place code ...
 1         Airport codes                IATA airport code ICAO airport code
 2         Country codes  IANA country code ISO 3166-1 alpha-2 alpha-3 n...
 3   Geodesicplace codes  Global C-squares Geohash Geohash-36 GEOREF Int...
 4                Global  C-squares Geohash Geohash-36 GEOREF Internatio...
 5              Regional  ICES Statistical Rectangles (north-east Atlant...
 6          Postal codes  Australian post codes CEP (Brazil) Eircodes (R...
 7             Telephony  ITU-R country codes ITU-T country calling code...
 8         Amateur radio  Maidenhead Locator System Historical : QRA loc...,
           0                                                  1
 0    Global  C-squares Geohash Geohash-36 GEOREF Internatio...
 1  Regional  ICES Statistical Rectangles (north-east Atlant...]

In [119]:
state_fips = state_tables[0]
state_fips.head()

,Name,Alpha code,Numeric code,Status
0,Alabama,AL,1,State; counties
1,Alaska,AK,2,State; boroughs
2,American Samoa,AS,60,Outlying area under U.S. sovereignty
3,American Samoa *,NaN,3,(FIPS 5-1 reserved code)
4,Arizona,AZ,4,State; counties